version: '3.8'

services:
  # Service PostgreSQL
  db:
    image: postgres:15
    # container_name: traduction
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    # ports:
      # - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U traduction_user"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

  # Service FastAPI
  app:
    build: .
    # container_name: traduction_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${NAME}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      SK: ${SK}
      ALG: ${ALG}
      HF_TOKEN: ${HF_TOKEN:token}
      # ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

